name: deploy to lambda
on:
  push:
    branches:
      - master
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Dependencies
        run: bin/setup
      - name: Build Archive
        run: bin/archive
      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.AWS_FUNCTION_NAME }}
          zip_file: tmp/archive.zip